# Generated by Django 5.1 on 2026-02-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/extra/')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.dish')),
            ],
        ),
    ]
